source 'http://rubygems.org'

gem 'rspec', '>=2.4'
gem 'ruby-debug19'
gem 'autotest'
gem 'autotest-growl'
gem 'rake'
gem 'kramdown'
gem 'gollum'
gem 'RedCloth'
gem 'redcarpet', '1.17.2'
gem 'colored'
gem 'reek'
